Repository chanson02/KnO3, pull requests merged in 2023-11, with the labels that each got.

#6 Create rust.yml
  .github/workflows/rust.yml
Labels: enhancement

#22 2 write pseudo code for board representation
  src/board.rs
Labels: enhancement

#23 pseudo-code for minimax function, min and max functions
  src/board.rs
  src/main.rs
Labels: enhancement

#32 9 write pseudo code for evaluating positions
  src/evaluate.rs
Labels: enhancement

#30 11 create fen function under board struct
  .github/workflows/rust.yml
  src/board.rs
  src/fen_util.rs
  src/main.rs
Labels: enhancement

#38 35 change vector to array in to string
  src/board.rs
  src/fen_util.rs
Labels: enhancement

#40 Added linting and auditing to our CI pipeline
  .github/workflows/rust.yml
  src/board.rs
  src/fen_util.rs
  src/main.rs
Labels: enhancement, good first issue

#41 31 valid fen
  Cargo.toml
  src/fen_util.rs
Labels: enhancement

#44 Fixed some referencing issues
  src/board.rs
Labels: enhancement, good first issue

#42 36 make docstrings uniform for board representation
  src/board.rs
  src/fen_util.rs
Labels: documentation

#47 13 implement rules of the game movement
  src/board.rs
  src/main.rs
Labels: enhancement

#53 50 bug castling rights only go up!
  src/board.rs
  src/fen_util.rs
  src/main.rs
Labels: bug

#55 Fen passant bug fixes
  src/board.rs
  src/fen_util.rs
Labels: bug
