Repository chanson02/KnO3, pull requests merged in 2023-12, with the labels that each got.

#56 33 fen tests
  src/board.rs
  src/fen_util.rs
  src/lib.rs
  tests/fen_tests.rs
  tests/util_tests.rs
Labels: test

#61 54 bug placed pieces do not over write
  src/board.rs
  src/fen_util.rs
Labels: bug

#66 45 implement legal moves updated
  src/board.rs
  src/board/piece.rs
  src/main.rs
  tests/legal_move_tests.rs
Labels: enhancement
